# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `googleapis-common-protos-types` gem.
# Please instead update this file by running `bin/tapioca gem googleapis-common-protos-types`.


# source://googleapis-common-protos-types//lib/google/api/http_pb.rb#34
module Google; end

# source://googleapis-common-protos-types//lib/google/api/http_pb.rb#35
module Google::Api; end

module Google::Api::ClientLibraryDestination
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#55
Google::Api::ClientLibraryDestination::CLIENT_LIBRARY_DESTINATION_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#55
Google::Api::ClientLibraryDestination::GITHUB = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#55
Google::Api::ClientLibraryDestination::PACKAGE_MANAGER = T.let(T.unsafe(nil), Integer)

module Google::Api::ClientLibraryOrganization
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::ADS = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::CLIENT_LIBRARY_ORGANIZATION_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::CLOUD = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::GENERATIVE_AI = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::GEO = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::PHOTOS = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::SHOPPING = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/client_pb.rb#54
Google::Api::ClientLibraryOrganization::STREET_VIEW = T.let(T.unsafe(nil), Integer)

class Google::Api::ClientLibrarySettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::CommonLanguageSettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::CppSettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::CustomHttpPattern < ::Google::Protobuf::AbstractMessage; end
class Google::Api::DotnetSettings < ::Google::Protobuf::AbstractMessage; end

module Google::Api::FieldBehavior
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::FIELD_BEHAVIOR_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::IDENTIFIER = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::IMMUTABLE = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::INPUT_ONLY = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::NON_EMPTY_DEFAULT = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::OPTIONAL = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::OUTPUT_ONLY = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::REQUIRED = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/field_behavior_pb.rb#38
Google::Api::FieldBehavior::UNORDERED_LIST = T.let(T.unsafe(nil), Integer)

class Google::Api::GoSettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::Http < ::Google::Protobuf::AbstractMessage; end
class Google::Api::HttpRule < ::Google::Protobuf::AbstractMessage; end
class Google::Api::JavaSettings < ::Google::Protobuf::AbstractMessage; end

module Google::Api::LaunchStage
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::ALPHA = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::BETA = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::DEPRECATED = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::EARLY_ACCESS = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::GA = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::LAUNCH_STAGE_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::PRELAUNCH = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/launch_stage_pb.rb#36
Google::Api::LaunchStage::UNIMPLEMENTED = T.let(T.unsafe(nil), Integer)

class Google::Api::MethodSettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::MethodSettings::LongRunning < ::Google::Protobuf::AbstractMessage; end
class Google::Api::NodeSettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::PhpSettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::Publishing < ::Google::Protobuf::AbstractMessage; end
class Google::Api::PythonSettings < ::Google::Protobuf::AbstractMessage; end
class Google::Api::ResourceDescriptor < ::Google::Protobuf::AbstractMessage; end

module Google::Api::ResourceDescriptor::History
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

# source://googleapis-common-protos-types//lib/google/api/resource_pb.rb#39
Google::Api::ResourceDescriptor::History::FUTURE_MULTI_PATTERN = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/resource_pb.rb#39
Google::Api::ResourceDescriptor::History::HISTORY_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/resource_pb.rb#39
Google::Api::ResourceDescriptor::History::ORIGINALLY_SINGLE_PATTERN = T.let(T.unsafe(nil), Integer)

module Google::Api::ResourceDescriptor::Style
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

# source://googleapis-common-protos-types//lib/google/api/resource_pb.rb#40
Google::Api::ResourceDescriptor::Style::DECLARATIVE_FRIENDLY = T.let(T.unsafe(nil), Integer)

# source://googleapis-common-protos-types//lib/google/api/resource_pb.rb#40
Google::Api::ResourceDescriptor::Style::STYLE_UNSPECIFIED = T.let(T.unsafe(nil), Integer)

class Google::Api::ResourceReference < ::Google::Protobuf::AbstractMessage; end
class Google::Api::RubySettings < ::Google::Protobuf::AbstractMessage; end

# source://googleapis-common-protos-types//lib/google/rpc/error_details_pb.rb#38
module Google::Rpc; end

class Google::Rpc::BadRequest < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::BadRequest::FieldViolation < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::DebugInfo < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::ErrorInfo < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::Help < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::Help::Link < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::LocalizedMessage < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::PreconditionFailure < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::PreconditionFailure::Violation < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::QuotaFailure < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::QuotaFailure::Violation < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::RequestInfo < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::ResourceInfo < ::Google::Protobuf::AbstractMessage; end
class Google::Rpc::RetryInfo < ::Google::Protobuf::AbstractMessage; end

# source://googleapis-common-protos-types//lib/google/type/expr_pb.rb#35
module Google::Type; end

class Google::Type::Expr < ::Google::Protobuf::AbstractMessage; end
