# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `grpc-google-iam-v1` gem.
# Please instead update this file by running `bin/tapioca gem grpc-google-iam-v1`.


class Google::Iam::V1::AuditConfig < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::AuditConfigDelta < ::Google::Protobuf::AbstractMessage; end

module Google::Iam::V1::AuditConfigDelta::Action
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

class Google::Iam::V1::AuditLogConfig < ::Google::Protobuf::AbstractMessage; end

module Google::Iam::V1::AuditLogConfig::LogType
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

class Google::Iam::V1::Binding < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::BindingDelta < ::Google::Protobuf::AbstractMessage; end

module Google::Iam::V1::BindingDelta::Action
  class << self
    def descriptor; end
    def lookup(_arg0); end
    def resolve(_arg0); end
  end
end

class Google::Iam::V1::GetIamPolicyRequest < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::GetPolicyOptions < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::Policy < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::PolicyDelta < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::SetIamPolicyRequest < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::TestIamPermissionsRequest < ::Google::Protobuf::AbstractMessage; end
class Google::Iam::V1::TestIamPermissionsResponse < ::Google::Protobuf::AbstractMessage; end
