openapi: 3.1.0
info:
  version: 1.0.0
  title: DrivePlug
servers:
  - url: https://your-domain.com
paths:
  /user.json:
    get:
      summary: Get identity of authenticated user
      operationId: getUserIdentity
      responses:
        "200":
          description: The authenticated user's identity
          content:
            application/json:
              schema:
                type: object
                required:
                  - display_name
                  - email
                properties:
                  display_name:
                    type: string
                  email:
                    type: string
  /memory.md:
    get:
      summary: Fetch your main memory
      operationId: getMainMemory
      responses:
        "200":
          description: The main memory in Markdown format
          content:
            text/x-markdown:
              schema:
                type: string
                description: The main memory in Markdown format
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Store the main memory
      operationId: writeMainMemory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The main memory content in Markdown format
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /meetings.md:
    post:
      summary: Log a meeting summary
      operationId: saveMeetingSummary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The meeting summary in Markdown format
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          enum:
            - success
            - error
        message:
          type: string
